# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kern_gauss <- function(x) {
    .Call('kdevine_kern_gauss', PACKAGE = 'kdevine', x)
}

ikern_gauss <- function(x) {
    .Call('kdevine_ikern_gauss', PACKAGE = 'kdevine', x)
}

eval_kde1d <- function(xsort, xev, xmin, xmax, bw) {
    .Call('kdevine_eval_kde1d', PACKAGE = 'kdevine', xsort, xev, xmin, xmax, bw)
}

eval_pkde1d <- function(x, xev, xmin, xmax, bw) {
    .Call('kdevine_eval_pkde1d', PACKAGE = 'kdevine', x, xev, xmin, xmax, bw)
}

eval_qkde1d <- function(x, qev, xmin, xmax, bw) {
    .Call('kdevine_eval_qkde1d', PACKAGE = 'kdevine', x, qev, xmin, xmax, bw)
}

